name: openvpn_flutter
description: Connect OpenVPN service with Flutter
version: 1.0.1
homepage: https://github.com/nizwar/openvpn_flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: id.laskarmedia.openvpn_flutter
        pluginClass: OpenVPNFlutterPlugin
      ios:
        pluginClass: OpenVPNFlutterPlugin
